#! /bin/sh

bspc config border_width         4
bspc config window_gap           50
bspc config top_padding		 24

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true
bspc config normal_border_color "#292b3c"
bspc config active_border_color "#3f3b48"
bspc config focused_border_color "#3f3b48"
bspc config presel_border_color "#292b3c"
bspc config urgent_border_color "#292b3c"
bspc config focused_locked_border_color "#292b3c"

bspc monitor -d 'www.' 'shell' 'games' 'chat' 'etc.'

bspc rule -a Gimp desktop=^8 state=floating follow=on
bspc rule -a Icecat desktop=^1
bspc rule -a mpv state=floating
bspc rule -a feh state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a org-bear-Launcher desktop=^5 state=floating
bspc rule -a Steam.exe desktop=^3 state=floating

PANEL_FIFO="/tmp/panel-fifo" panel &
